server:
  port: 8080

#springboot   mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mapper/config/sqlMapConfig.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/garbagecollection
    username: root
    password: wang336699
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
#  mvc:
#    view:
#      prefix: WEB-INF/jsp/
#      suffix: .jsp
